name: Build and deploy Python app to Azure Web App - bbgget

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and collect static files
        run: |
          source antenv/bin/activate
          cd booking
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bbgget'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CCC7A3477BD9492E884C71DE047D747B }}
          package: '.'

      - name: Configure Startup Command
        run: |
          az webapp config set \
            --resource-group YOUR_RESOURCE_GROUP \
            --name bbgget \
            --startup-file "gunicorn booking.booking.wsgi --bind=0.0.0.0:\$PORT --workers=2"
